import os
import re

PLUGIN_DIR = os.path.dirname(os.path.abspath(__file__))

# Patterns to identify file paths and executables
FILE_PATTERNS = [
    r'["\']([A-Za-z]:[\\/][^"\']+\.(csv|xlsx|gpkg|shp|dat|json|ctl|txt|rds|sav|xls|dbf))["\']',
    r'["\']([A-Za-z]:[\\/][^"\']+/[^"\']+\.(csv|xlsx|gpkg|shp|dat|json|ctl|txt|rds|sav|xls|dbf))["\']',
    r'["\']([A-Za-z]:[\\/][^"\']+/[^"\']+/[^"\']+\.(csv|xlsx|gpkg|shp|dat|json|ctl|txt|rds|sav|xls|dbf))["\']',
]
EXE_PATTERNS = [
    r'["\']([A-Za-z]:[\\/][^"\']+\.(exe|bat|sh|jar))["\']',
    r'jdk[_-]?(1\.[0-9]+|[0-9]+)',  # e.g., jdk_22, jdk_1.8, jdk-21
    r'java[_-]?(1\.[0-9]+|[0-9]+)',
]

# Patterns to ignore output files (look for 'output', 'write', 'save', etc.)
OUTPUT_HINTS = [
    r'output', r'write', r'save', r'fwrite', r'Out', r'_out', r'_output', r'_Out', r'_Output'
]

def is_output_line(line):
    return any(re.search(hint, line, re.IGNORECASE) for hint in OUTPUT_HINTS)

def scan_files():
    required_files = set()
    required_exes = set()
    for root, dirs, files in os.walk(PLUGIN_DIR):
        for fname in files:
            if fname.endswith('.py') or fname.endswith('.R'):
                fpath = os.path.join(root, fname)
                with open(fpath, encoding='utf-8', errors='ignore') as f:
                    for line in f:
                        # Skip lines that look like output file assignments
                        if is_output_line(line):
                            continue
                        # Find input file paths
                        for pat in FILE_PATTERNS:
                            for match in re.findall(pat, line):
                                required_files.add(match[0])
                        # Find executables
                        for pat in EXE_PATTERNS:
                            for match in re.findall(pat, line):
                                required_exes.add(match if isinstance(match, str) else match[0])
    return required_files, required_exes

def main():
    files, exes = scan_files()
    print("Required input files (not generated by scripts):")
    for f in sorted(files):
        print("  ", f)
    print("\nRequired executables or paths:")
    for e in sorted(exes):
        print("  ", e)

if __name__ == "__main__":
    main()