# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/General_Configuration.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_GenPrjSetting(object):
    def setupUi(self, Dialog_GenPrjSetting):
        Dialog_GenPrjSetting.setObjectName("Dialog_GenPrjSetting")
        Dialog_GenPrjSetting.setWindowModality(QtCore.Qt.NonModal)
        Dialog_GenPrjSetting.resize(649, 220)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_GenPrjSetting)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Dialog_GenPrjSetting)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.label_header = QtWidgets.QLabel(self.frame)
        self.label_header.setObjectName("label_header")
        self.gridLayout.addWidget(self.label_header, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_TSMloc = QtWidgets.QLabel(self.frame)
        self.label_TSMloc.setMinimumSize(QtCore.QSize(120, 0))
        self.label_TSMloc.setObjectName("label_TSMloc")
        self.horizontalLayout_3.addWidget(self.label_TSMloc)
        self.lineEdit_ModelPath = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_ModelPath.setObjectName("lineEdit_ModelPath")
        self.horizontalLayout_3.addWidget(self.lineEdit_ModelPath)
        self.pushButton_Browse_TSMPath = QtWidgets.QPushButton(self.frame)
        self.pushButton_Browse_TSMPath.setObjectName("pushButton_Browse_TSMPath")
        self.horizontalLayout_3.addWidget(self.pushButton_Browse_TSMPath)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_Plugins = QtWidgets.QLabel(self.frame)
        self.label_Plugins.setMinimumSize(QtCore.QSize(120, 0))
        self.label_Plugins.setObjectName("label_Plugins")
        self.horizontalLayout_2.addWidget(self.label_Plugins)
        self.lineEdit_PluginsPath = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_PluginsPath.setObjectName("lineEdit_PluginsPath")
        self.horizontalLayout_2.addWidget(self.lineEdit_PluginsPath)
        self.pushButton_Browse_PluginsPath = QtWidgets.QPushButton(self.frame)
        self.pushButton_Browse_PluginsPath.setObjectName("pushButton_Browse_PluginsPath")
        self.horizontalLayout_2.addWidget(self.pushButton_Browse_PluginsPath)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_NumProc = QtWidgets.QLabel(self.frame)
        self.label_NumProc.setMinimumSize(QtCore.QSize(120, 0))
        self.label_NumProc.setObjectName("label_NumProc")
        self.horizontalLayout_4.addWidget(self.label_NumProc)
        self.lineEdit_NumProcessors = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_NumProcessors.setObjectName("lineEdit_NumProcessors")
        self.horizontalLayout_4.addWidget(self.lineEdit_NumProcessors)
        spacerItem = QtWidgets.QSpacerItem(300, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.horizontalLayout_claude = QtWidgets.QHBoxLayout()
        self.horizontalLayout_claude.setObjectName("horizontalLayout_claude")
        self.pushButton_Claude = QtWidgets.QPushButton(self.frame)
        self.pushButton_Claude.setEnabled(False)
        self.pushButton_Claude.setObjectName("pushButton_Claude")
        self.horizontalLayout_claude.addWidget(self.pushButton_Claude)
        spacerItem1 = QtWidgets.QSpacerItem(300, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_claude.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_claude, 4, 0, 1, 1)
        self.buttonBox_GenConfig = QtWidgets.QDialogButtonBox(self.frame)
        self.buttonBox_GenConfig.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox_GenConfig.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_GenConfig.setObjectName("buttonBox_GenConfig")
        self.gridLayout.addWidget(self.buttonBox_GenConfig, 5, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Dialog_GenPrjSetting)
        QtCore.QMetaObject.connectSlotsByName(Dialog_GenPrjSetting)

    def retranslateUi(self, Dialog_GenPrjSetting):
        _translate = QtCore.QCoreApplication.translate
        Dialog_GenPrjSetting.setWindowTitle(_translate("Dialog_GenPrjSetting", "TSM Configuration"))
        self.label_header.setText(_translate("Dialog_GenPrjSetting", "Requirement: QGIS 3.0 or higher"))
        self.label_TSMloc.setText(_translate("Dialog_GenPrjSetting", "TSM Location"))
        self.lineEdit_ModelPath.setText(_translate("Dialog_GenPrjSetting", "C:/TSM_NextGen_v6"))
        self.pushButton_Browse_TSMPath.setText(_translate("Dialog_GenPrjSetting", "Browse"))
        self.label_Plugins.setText(_translate("Dialog_GenPrjSetting", "Plugins Path"))
        self.pushButton_Browse_PluginsPath.setText(_translate("Dialog_GenPrjSetting", "Browse"))
        self.label_NumProc.setText(_translate("Dialog_GenPrjSetting", "Number of Processors"))
        self.pushButton_Claude.setToolTip(_translate("Dialog_GenPrjSetting", "Bring Claude chat into QGIS (coming soon)"))
        self.pushButton_Claude.setText(_translate("Dialog_GenPrjSetting", "Ask Claude (coming soon)"))
