# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/hydra.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: regenerating this file with pyuic5 reintroduces the raw `PyQt5`
# import and unscoped Qt enums, which crash the dialog on QGIS 4 (Qt6).  After
# any regeneration, re-apply the two QGIS-4 fixes below (see 26bf53f):
#   1. import through the qgis.PyQt shim, not PyQt5 directly
#   2. fully scope every Qt enum (QFrame.StyledPanel -> QFrame.Shape.StyledPanel)
# Both forms are valid on PyQt5, so one code base runs on QGIS 3 and QGIS 4.


from qgis.PyQt import QtCore, QtGui, QtWidgets


class Ui_DialogHydra(object):
    def setupUi(self, DialogHydra):
        DialogHydra.setObjectName("DialogHydra")
        DialogHydra.resize(940, 560)
        self.topLayout = QtWidgets.QHBoxLayout(DialogHydra)
        self.topLayout.setObjectName("topLayout")
        self.frame = QtWidgets.QFrame(DialogHydra)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setObjectName("frame")
        self.leftLayout = QtWidgets.QVBoxLayout(self.frame)
        self.leftLayout.setObjectName("leftLayout")
        self.gridLayout_io = QtWidgets.QGridLayout()
        self.gridLayout_io.setObjectName("gridLayout_io")
        self.label_link = QtWidgets.QLabel(self.frame)
        self.label_link.setObjectName("label_link")
        self.gridLayout_io.addWidget(self.label_link, 0, 0, 1, 1)
        self.comboBox_LinkLayer = QtWidgets.QComboBox(self.frame)
        self.comboBox_LinkLayer.setObjectName("comboBox_LinkLayer")
        self.gridLayout_io.addWidget(self.comboBox_LinkLayer, 0, 1, 1, 2)
        self.label_node = QtWidgets.QLabel(self.frame)
        self.label_node.setObjectName("label_node")
        self.gridLayout_io.addWidget(self.label_node, 1, 0, 1, 1)
        self.comboBox_NodeLayer = QtWidgets.QComboBox(self.frame)
        self.comboBox_NodeLayer.setObjectName("comboBox_NodeLayer")
        self.gridLayout_io.addWidget(self.comboBox_NodeLayer, 1, 1, 1, 2)
        self.label_trip = QtWidgets.QLabel(self.frame)
        self.label_trip.setObjectName("label_trip")
        self.gridLayout_io.addWidget(self.label_trip, 2, 0, 1, 1)
        self.lineEdit_TripFile = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_TripFile.setObjectName("lineEdit_TripFile")
        self.gridLayout_io.addWidget(self.lineEdit_TripFile, 2, 1, 1, 1)
        self.browse_TripFile = QtWidgets.QPushButton(self.frame)
        self.browse_TripFile.setObjectName("browse_TripFile")
        self.gridLayout_io.addWidget(self.browse_TripFile, 2, 2, 1, 1)
        self.label_outdir = QtWidgets.QLabel(self.frame)
        self.label_outdir.setObjectName("label_outdir")
        self.gridLayout_io.addWidget(self.label_outdir, 3, 0, 1, 1)
        self.lineEdit_OutDir = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_OutDir.setObjectName("lineEdit_OutDir")
        self.gridLayout_io.addWidget(self.lineEdit_OutDir, 3, 1, 1, 1)
        self.browse_OutDir = QtWidgets.QPushButton(self.frame)
        self.browse_OutDir.setObjectName("browse_OutDir")
        self.gridLayout_io.addWidget(self.browse_OutDir, 3, 2, 1, 1)
        self.leftLayout.addLayout(self.gridLayout_io)
        self.macroLayout = QtWidgets.QHBoxLayout()
        self.macroLayout.setObjectName("macroLayout")
        self.label_macro = QtWidgets.QLabel(self.frame)
        self.label_macro.setObjectName("label_macro")
        self.macroLayout.addWidget(self.label_macro)
        self.comboBox_Macro = QtWidgets.QComboBox(self.frame)
        self.comboBox_Macro.setObjectName("comboBox_Macro")
        self.comboBox_Macro.addItem("")
        self.comboBox_Macro.addItem("")
        self.comboBox_Macro.addItem("")
        self.macroLayout.addWidget(self.comboBox_Macro)
        self.leftLayout.addLayout(self.macroLayout)
        self.groupBox_Equil = QtWidgets.QGroupBox(self.frame)
        self.groupBox_Equil.setObjectName("groupBox_Equil")
        self.gridLayout_eq = QtWidgets.QGridLayout(self.groupBox_Equil)
        self.gridLayout_eq.setObjectName("gridLayout_eq")
        self.label_iters = QtWidgets.QLabel(self.groupBox_Equil)
        self.label_iters.setObjectName("label_iters")
        self.gridLayout_eq.addWidget(self.label_iters, 0, 0, 1, 1)
        self.lineEdit_Iters = QtWidgets.QLineEdit(self.groupBox_Equil)
        self.lineEdit_Iters.setObjectName("lineEdit_Iters")
        self.gridLayout_eq.addWidget(self.lineEdit_Iters, 0, 1, 1, 1)
        self.label_gap = QtWidgets.QLabel(self.groupBox_Equil)
        self.label_gap.setObjectName("label_gap")
        self.gridLayout_eq.addWidget(self.label_gap, 0, 2, 1, 1)
        self.lineEdit_Gap = QtWidgets.QLineEdit(self.groupBox_Equil)
        self.lineEdit_Gap.setObjectName("lineEdit_Gap")
        self.gridLayout_eq.addWidget(self.lineEdit_Gap, 0, 3, 1, 1)
        self.label_chunks = QtWidgets.QLabel(self.groupBox_Equil)
        self.label_chunks.setObjectName("label_chunks")
        self.gridLayout_eq.addWidget(self.label_chunks, 1, 0, 1, 1)
        self.lineEdit_Chunks = QtWidgets.QLineEdit(self.groupBox_Equil)
        self.lineEdit_Chunks.setObjectName("lineEdit_Chunks")
        self.gridLayout_eq.addWidget(self.lineEdit_Chunks, 1, 1, 1, 1)
        self.label_threads = QtWidgets.QLabel(self.groupBox_Equil)
        self.label_threads.setObjectName("label_threads")
        self.gridLayout_eq.addWidget(self.label_threads, 1, 2, 1, 1)
        self.lineEdit_Threads = QtWidgets.QLineEdit(self.groupBox_Equil)
        self.lineEdit_Threads.setObjectName("lineEdit_Threads")
        self.gridLayout_eq.addWidget(self.lineEdit_Threads, 1, 3, 1, 1)
        self.label_nodesched = QtWidgets.QLabel(self.groupBox_Equil)
        self.label_nodesched.setObjectName("label_nodesched")
        self.gridLayout_eq.addWidget(self.label_nodesched, 2, 0, 1, 1)
        self.comboBox_NodeSchedule = QtWidgets.QComboBox(self.groupBox_Equil)
        self.comboBox_NodeSchedule.setObjectName("comboBox_NodeSchedule")
        self.comboBox_NodeSchedule.addItem("")
        self.comboBox_NodeSchedule.addItem("")
        self.comboBox_NodeSchedule.addItem("")
        self.gridLayout_eq.addWidget(self.comboBox_NodeSchedule, 2, 1, 1, 3)
        self.leftLayout.addWidget(self.groupBox_Equil)
        self.groupBox_MesoMicro = QtWidgets.QGroupBox(self.frame)
        self.groupBox_MesoMicro.setObjectName("groupBox_MesoMicro")
        self.gridLayout_mm = QtWidgets.QGridLayout(self.groupBox_MesoMicro)
        self.gridLayout_mm.setObjectName("gridLayout_mm")
        self.label_meso = QtWidgets.QLabel(self.groupBox_MesoMicro)
        self.label_meso.setObjectName("label_meso")
        self.gridLayout_mm.addWidget(self.label_meso, 0, 0, 1, 1)
        self.lineEdit_MesoFtypes = QtWidgets.QLineEdit(self.groupBox_MesoMicro)
        self.lineEdit_MesoFtypes.setObjectName("lineEdit_MesoFtypes")
        self.gridLayout_mm.addWidget(self.lineEdit_MesoFtypes, 0, 1, 1, 3)
        self.checkBox_Micro = QtWidgets.QCheckBox(self.groupBox_MesoMicro)
        self.checkBox_Micro.setObjectName("checkBox_Micro")
        self.gridLayout_mm.addWidget(self.checkBox_Micro, 1, 0, 1, 1)
        self.lineEdit_MicroFtypes = QtWidgets.QLineEdit(self.groupBox_MesoMicro)
        self.lineEdit_MicroFtypes.setEnabled(False)
        self.lineEdit_MicroFtypes.setObjectName("lineEdit_MicroFtypes")
        self.gridLayout_mm.addWidget(self.lineEdit_MicroFtypes, 1, 1, 1, 1)
        self.label_coupling = QtWidgets.QLabel(self.groupBox_MesoMicro)
        self.label_coupling.setObjectName("label_coupling")
        self.gridLayout_mm.addWidget(self.label_coupling, 1, 2, 1, 1)
        self.comboBox_Coupling = QtWidgets.QComboBox(self.groupBox_MesoMicro)
        self.comboBox_Coupling.setEnabled(False)
        self.comboBox_Coupling.setObjectName("comboBox_Coupling")
        self.comboBox_Coupling.addItem("")
        self.comboBox_Coupling.addItem("")
        self.comboBox_Coupling.addItem("")
        self.gridLayout_mm.addWidget(self.comboBox_Coupling, 1, 3, 1, 1)
        self.label_microchoice = QtWidgets.QLabel(self.groupBox_MesoMicro)
        self.label_microchoice.setObjectName("label_microchoice")
        self.gridLayout_mm.addWidget(self.label_microchoice, 2, 0, 1, 1)
        self.comboBox_MicroChoice = QtWidgets.QComboBox(self.groupBox_MesoMicro)
        self.comboBox_MicroChoice.setEnabled(False)
        self.comboBox_MicroChoice.setObjectName("comboBox_MicroChoice")
        self.comboBox_MicroChoice.addItem("")
        self.comboBox_MicroChoice.addItem("")
        self.gridLayout_mm.addWidget(self.comboBox_MicroChoice, 2, 1, 1, 3)
        self.leftLayout.addWidget(self.groupBox_MesoMicro)
        self.segParamLayout = QtWidgets.QHBoxLayout()
        self.segParamLayout.setObjectName("segParamLayout")
        self.label_segparam = QtWidgets.QLabel(self.frame)
        self.label_segparam.setObjectName("label_segparam")
        self.segParamLayout.addWidget(self.label_segparam)
        self.lineEdit_SegParams = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_SegParams.setObjectName("lineEdit_SegParams")
        self.segParamLayout.addWidget(self.lineEdit_SegParams)
        self.browse_SegParams = QtWidgets.QPushButton(self.frame)
        self.browse_SegParams.setObjectName("browse_SegParams")
        self.segParamLayout.addWidget(self.browse_SegParams)
        self.leftLayout.addLayout(self.segParamLayout)
        self.tollLayout = QtWidgets.QHBoxLayout()
        self.tollLayout.setObjectName("tollLayout")
        self.label_toll = QtWidgets.QLabel(self.frame)
        self.label_toll.setObjectName("label_toll")
        self.tollLayout.addWidget(self.label_toll)
        self.lineEdit_TollPolicy = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_TollPolicy.setObjectName("lineEdit_TollPolicy")
        self.tollLayout.addWidget(self.lineEdit_TollPolicy)
        self.browse_TollPolicy = QtWidgets.QPushButton(self.frame)
        self.browse_TollPolicy.setObjectName("browse_TollPolicy")
        self.tollLayout.addWidget(self.browse_TollPolicy)
        self.leftLayout.addLayout(self.tollLayout)
        self.groupBox_Advanced = QtWidgets.QGroupBox(self.frame)
        self.groupBox_Advanced.setObjectName("groupBox_Advanced")
        self.gridLayout_adv = QtWidgets.QGridLayout(self.groupBox_Advanced)
        self.gridLayout_adv.setObjectName("gridLayout_adv")
        self.label_rerouteFrac = QtWidgets.QLabel(self.groupBox_Advanced)
        self.label_rerouteFrac.setObjectName("label_rerouteFrac")
        self.gridLayout_adv.addWidget(self.label_rerouteFrac, 0, 0, 1, 1)
        self.lineEdit_RerouteFraction = QtWidgets.QLineEdit(self.groupBox_Advanced)
        self.lineEdit_RerouteFraction.setObjectName("lineEdit_RerouteFraction")
        self.gridLayout_adv.addWidget(self.lineEdit_RerouteFraction, 0, 1, 1, 1)
        self.label_rerouteThr = QtWidgets.QLabel(self.groupBox_Advanced)
        self.label_rerouteThr.setObjectName("label_rerouteThr")
        self.gridLayout_adv.addWidget(self.label_rerouteThr, 0, 2, 1, 1)
        self.lineEdit_RerouteThreshold = QtWidgets.QLineEdit(self.groupBox_Advanced)
        self.lineEdit_RerouteThreshold.setObjectName("lineEdit_RerouteThreshold")
        self.gridLayout_adv.addWidget(self.lineEdit_RerouteThreshold, 0, 3, 1, 1)
        self.label_spillback = QtWidgets.QLabel(self.groupBox_Advanced)
        self.label_spillback.setObjectName("label_spillback")
        self.gridLayout_adv.addWidget(self.label_spillback, 1, 0, 1, 1)
        self.lineEdit_LtmSpillback = QtWidgets.QLineEdit(self.groupBox_Advanced)
        self.lineEdit_LtmSpillback.setObjectName("lineEdit_LtmSpillback")
        self.gridLayout_adv.addWidget(self.lineEdit_LtmSpillback, 1, 1, 1, 1)
        self.label_jam = QtWidgets.QLabel(self.groupBox_Advanced)
        self.label_jam.setObjectName("label_jam")
        self.gridLayout_adv.addWidget(self.label_jam, 1, 2, 1, 1)
        self.lineEdit_JamDensity = QtWidgets.QLineEdit(self.groupBox_Advanced)
        self.lineEdit_JamDensity.setObjectName("lineEdit_JamDensity")
        self.gridLayout_adv.addWidget(self.lineEdit_JamDensity, 1, 3, 1, 1)
        self.label_maxtrips = QtWidgets.QLabel(self.groupBox_Advanced)
        self.label_maxtrips.setObjectName("label_maxtrips")
        self.gridLayout_adv.addWidget(self.label_maxtrips, 2, 0, 1, 1)
        self.lineEdit_MaxTrips = QtWidgets.QLineEdit(self.groupBox_Advanced)
        self.lineEdit_MaxTrips.setObjectName("lineEdit_MaxTrips")
        self.gridLayout_adv.addWidget(self.lineEdit_MaxTrips, 2, 1, 1, 1)
        self.label_sample = QtWidgets.QLabel(self.groupBox_Advanced)
        self.label_sample.setObjectName("label_sample")
        self.gridLayout_adv.addWidget(self.label_sample, 2, 2, 1, 1)
        self.lineEdit_SampleEvery = QtWidgets.QLineEdit(self.groupBox_Advanced)
        self.lineEdit_SampleEvery.setObjectName("lineEdit_SampleEvery")
        self.gridLayout_adv.addWidget(self.lineEdit_SampleEvery, 2, 3, 1, 1)
        self.label_sampleSched = QtWidgets.QLabel(self.groupBox_Advanced)
        self.label_sampleSched.setObjectName("label_sampleSched")
        self.gridLayout_adv.addWidget(self.label_sampleSched, 3, 0, 1, 1)
        self.comboBox_SampleSchedule = QtWidgets.QComboBox(self.groupBox_Advanced)
        self.comboBox_SampleSchedule.setObjectName("comboBox_SampleSchedule")
        self.comboBox_SampleSchedule.addItem("")
        self.comboBox_SampleSchedule.addItem("")
        self.comboBox_SampleSchedule.addItem("")
        self.gridLayout_adv.addWidget(self.comboBox_SampleSchedule, 3, 1, 1, 1)
        self.label_sampleCustom = QtWidgets.QLabel(self.groupBox_Advanced)
        self.label_sampleCustom.setObjectName("label_sampleCustom")
        self.gridLayout_adv.addWidget(self.label_sampleCustom, 3, 2, 1, 1)
        self.lineEdit_SampleSchedule = QtWidgets.QLineEdit(self.groupBox_Advanced)
        self.lineEdit_SampleSchedule.setObjectName("lineEdit_SampleSchedule")
        self.gridLayout_adv.addWidget(self.lineEdit_SampleSchedule, 3, 3, 1, 1)
        self.checkBox_Checkpoint = QtWidgets.QCheckBox(self.groupBox_Advanced)
        self.checkBox_Checkpoint.setChecked(True)
        self.checkBox_Checkpoint.setObjectName("checkBox_Checkpoint")
        self.gridLayout_adv.addWidget(self.checkBox_Checkpoint, 4, 0, 1, 2)
        self.label_ckptEvery = QtWidgets.QLabel(self.groupBox_Advanced)
        self.label_ckptEvery.setObjectName("label_ckptEvery")
        self.gridLayout_adv.addWidget(self.label_ckptEvery, 4, 2, 1, 1)
        self.lineEdit_CheckpointEvery = QtWidgets.QLineEdit(self.groupBox_Advanced)
        self.lineEdit_CheckpointEvery.setObjectName("lineEdit_CheckpointEvery")
        self.gridLayout_adv.addWidget(self.lineEdit_CheckpointEvery, 4, 3, 1, 1)
        self.leftLayout.addWidget(self.groupBox_Advanced)
        self.groupBox_Outputs = QtWidgets.QGroupBox(self.frame)
        self.groupBox_Outputs.setObjectName("groupBox_Outputs")
        self.gridLayout_out = QtWidgets.QGridLayout(self.groupBox_Outputs)
        self.gridLayout_out.setObjectName("gridLayout_out")
        self.checkBox_AgentPlans = QtWidgets.QCheckBox(self.groupBox_Outputs)
        self.checkBox_AgentPlans.setChecked(True)
        self.checkBox_AgentPlans.setObjectName("checkBox_AgentPlans")
        self.gridLayout_out.addWidget(self.checkBox_AgentPlans, 0, 0, 1, 1)
        self.checkBox_AgentPaths = QtWidgets.QCheckBox(self.groupBox_Outputs)
        self.checkBox_AgentPaths.setChecked(True)
        self.checkBox_AgentPaths.setObjectName("checkBox_AgentPaths")
        self.gridLayout_out.addWidget(self.checkBox_AgentPaths, 0, 1, 1, 1)
        self.leftLayout.addWidget(self.groupBox_Outputs)
        self.runLayout = QtWidgets.QHBoxLayout()
        self.runLayout.setObjectName("runLayout")
        self.run_Hydra = QtWidgets.QPushButton(self.frame)
        self.run_Hydra.setObjectName("run_Hydra")
        self.runLayout.addWidget(self.run_Hydra)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.frame)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.runLayout.addWidget(self.buttonBox)
        self.leftLayout.addLayout(self.runLayout)
        self.topLayout.addWidget(self.frame)
        self.textBrowser = QtWidgets.QTextBrowser(DialogHydra)
        self.textBrowser.setMinimumSize(QtCore.QSize(320, 0))
        self.textBrowser.setOpenExternalLinks(True)
        self.textBrowser.setObjectName("textBrowser")
        self.topLayout.addWidget(self.textBrowser)

        self.retranslateUi(DialogHydra)
        self.comboBox_Macro.setCurrentIndex(2)
        self.comboBox_NodeSchedule.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(DialogHydra)

    def retranslateUi(self, DialogHydra):
        _translate = QtCore.QCoreApplication.translate
        DialogHydra.setWindowTitle(_translate("DialogHydra", "HyDRA (AgentFlow-DTA)"))
        self.label_link.setText(_translate("DialogHydra", "Link layer (GeoPackage)"))
        self.label_node.setText(_translate("DialogHydra", "Node layer (GeoPackage)"))
        self.label_trip.setText(_translate("DialogHydra", "Trip list (.csv.gz)"))
        self.browse_TripFile.setText(_translate("DialogHydra", "..."))
        self.label_outdir.setText(_translate("DialogHydra", "Output directory"))
        self.lineEdit_OutDir.setPlaceholderText(_translate("DialogHydra", "(defaults to the scenario directory)"))
        self.lineEdit_OutDir.setToolTip(_translate("DialogHydra", "All HyDRA outputs (control file, log, link performance, agent plans/paths, checkpoint) are written here. Leave blank to use the scenario directory."))
        self.browse_OutDir.setText(_translate("DialogHydra", "..."))
        self.label_macro.setText(_translate("DialogHydra", "Run Mode (flow model)"))
        self.comboBox_Macro.setToolTip(_translate("DialogHydra", "Preset configures the DNL flow model plus meso/micro defaults."))
        self.comboBox_Macro.setItemText(0, _translate("DialogHydra", "PointQueue + BPR"))
        self.comboBox_Macro.setItemText(1, _translate("DialogHydra", "Node + PointQueue (nodeDNL)"))
        self.comboBox_Macro.setItemText(2, _translate("DialogHydra", "Node + Spatial/LTM (nodeDNL)"))
        self.groupBox_Equil.setTitle(_translate("DialogHydra", "Equilibrium"))
        self.label_iters.setText(_translate("DialogHydra", "Max Iterations"))
        self.lineEdit_Iters.setText(_translate("DialogHydra", "10"))
        self.label_gap.setText(_translate("DialogHydra", "Relative Gap"))
        self.lineEdit_Gap.setText(_translate("DialogHydra", "0.01"))
        self.label_chunks.setText(_translate("DialogHydra", "Route Chunks"))
        self.lineEdit_Chunks.setText(_translate("DialogHydra", "10"))
        self.label_threads.setText(_translate("DialogHydra", "Threads (0=all)"))
        self.lineEdit_Threads.setText(_translate("DialogHydra", "0"))
        self.label_nodesched.setText(_translate("DialogHydra", "Node refresh"))
        self.comboBox_NodeSchedule.setToolTip(_translate("DialogHydra", "Node-DNL refresh stride for the DTA_Node* loaders: per_iter (fast, statewide), per_chunk (tight, county), or a hybrid ramp."))
        self.comboBox_NodeSchedule.setItemText(0, _translate("DialogHydra", "Per iteration (fast - statewide)"))
        self.comboBox_NodeSchedule.setItemText(1, _translate("DialogHydra", "Per chunk (tight - county)"))
        self.comboBox_NodeSchedule.setItemText(2, _translate("DialogHydra", "Hybrid (per-iter -> per-chunk)"))
        self.groupBox_MesoMicro.setTitle(_translate("DialogHydra", "Meso / Micro"))
        self.label_meso.setText(_translate("DialogHydra", "Meso FTYPEs"))
        self.lineEdit_MesoFtypes.setToolTip(_translate("DialogHydra", "Comma-separated FTYPEs run as meso. Default: the limited-access system - freeways 11/12, ramps 71-79, toll roads 91-94, express lanes 96-98."))
        self.checkBox_Micro.setText(_translate("DialogHydra", "Micro corridor"))
        self.lineEdit_MicroFtypes.setToolTip(_translate("DialogHydra", "FTYPEs tagged for the lane-level micro sim."))
        self.label_coupling.setText(_translate("DialogHydra", "Coupling"))
        self.comboBox_Coupling.setItemText(0, _translate("DialogHydra", "oneway"))
        self.comboBox_Coupling.setItemText(1, _translate("DialogHydra", "twoway_frozen"))
        self.comboBox_Coupling.setItemText(2, _translate("DialogHydra", "twoway_full"))
        self.label_microchoice.setText(_translate("DialogHydra", "EL/GP choice"))
        self.comboBox_MicroChoice.setToolTip(_translate("DialogHydra", "How EL vs GP is chosen inside a micro corridor: meso logit, or micro time-differential converted by each agent\'s VOT."))
        self.comboBox_MicroChoice.setItemText(0, _translate("DialogHydra", "Meso logit"))
        self.comboBox_MicroChoice.setItemText(1, _translate("DialogHydra", "Micro time-differential (VOT)"))
        self.label_segparam.setText(_translate("DialogHydra", "Market Segments VOT (CSV)"))
        self.lineEdit_SegParams.setToolTip(_translate("DialogHydra", "Market/VOT segment generalized-cost parameters: beta_time, beta_cost, distance (SEGMENT_PARAM_FILE). Without it, generalized cost = travel time only. This is NOT the toll policy file."))
        self.browse_SegParams.setText(_translate("DialogHydra", "..."))
        self.label_toll.setText(_translate("DialogHydra", "Toll policy (CSV)"))
        self.lineEdit_TollPolicy.setToolTip(_translate("DialogHydra", "Time-of-day tolls / EL toll curves (TOLL_POLICY_FILE). Optional."))
        self.browse_TollPolicy.setText(_translate("DialogHydra", "..."))
        self.groupBox_Advanced.setTitle(_translate("DialogHydra", "Advanced (afdta) — rerouting, LTM, sampling"))
        self.label_rerouteFrac.setText(_translate("DialogHydra", "Reroute fraction (min)"))
        self.lineEdit_RerouteFraction.setText(_translate("DialogHydra", "0.05"))
        self.lineEdit_RerouteFraction.setToolTip(_translate("DialogHydra", "REROUTE_FRACTION_MIN — minimum share of agents rerouted per iteration."))
        self.label_rerouteThr.setText(_translate("DialogHydra", "Reroute threshold (min)"))
        self.lineEdit_RerouteThreshold.setText(_translate("DialogHydra", "0.01"))
        self.lineEdit_RerouteThreshold.setToolTip(_translate("DialogHydra", "REROUTE_THRESHOLD_MIN — minimum travel-time improvement (min) to switch an agent\'s route."))
        self.label_spillback.setText(_translate("DialogHydra", "LTM max spillback (min)"))
        self.lineEdit_LtmSpillback.setText(_translate("DialogHydra", "20"))
        self.lineEdit_LtmSpillback.setToolTip(_translate("DialogHydra", "LTM_MAX_SPILLBACK_MIN — cap on queue spillback propagation (minutes). LTM macro only."))
        self.label_jam.setText(_translate("DialogHydra", "Jam density"))
        self.lineEdit_JamDensity.setText(_translate("DialogHydra", "240"))
        self.lineEdit_JamDensity.setToolTip(_translate("DialogHydra", "JAM_DENSITY — veh/mi/lane at jam (LTM)."))
        self.label_maxtrips.setText(_translate("DialogHydra", "Max trips (0=all)"))
        self.lineEdit_MaxTrips.setText(_translate("DialogHydra", "0"))
        self.lineEdit_MaxTrips.setToolTip(_translate("DialogHydra", "MAX_TRIPS — cap trips loaded (0 = all). Use for quick test runs."))
        self.label_sample.setText(_translate("DialogHydra", "Sample every"))
        self.lineEdit_SampleEvery.setText(_translate("DialogHydra", "1"))
        self.label_sampleSched.setText(_translate("DialogHydra", "Sampling schedule"))
        self.comboBox_SampleSchedule.setItemText(0, _translate("DialogHydra", "Progressive (25 -> 50 -> 100%)"))
        self.comboBox_SampleSchedule.setItemText(1, _translate("DialogHydra", "Full sample every iteration"))
        self.comboBox_SampleSchedule.setItemText(2, _translate("DialogHydra", "Custom"))
        self.label_sampleCustom.setText(_translate("DialogHydra", "Custom schedule"))
        self.lineEdit_SampleSchedule.setPlaceholderText(_translate("DialogHydra", "1-4:25, 5-8:50, 9-15:100"))
        self.checkBox_Checkpoint.setText(_translate("DialogHydra", "Write checkpoint (enables warm restart)"))
        self.label_ckptEvery.setText(_translate("DialogHydra", "Checkpoint every"))
        self.lineEdit_CheckpointEvery.setText(_translate("DialogHydra", "3"))
        self.lineEdit_SampleEvery.setToolTip(_translate("DialogHydra", "SAMPLE_EVERY — load every Nth trip (1 = all)."))
        self.groupBox_Outputs.setTitle(_translate("DialogHydra", "Outputs (link performance by macro/meso/micro is always written)"))
        self.checkBox_AgentPlans.setToolTip(_translate("DialogHydra", "Light per-agent summary (agentPlans_out.csv). Uncheck to skip."))
        self.checkBox_AgentPlans.setText(_translate("DialogHydra", "Agent plans (agentPlans_out.csv)"))
        self.checkBox_AgentPaths.setToolTip(_translate("DialogHydra", "Full per-agent paths (agentPaths.duckdb, large). Feeds agentAnalysis select-link / trace / tiers. Uncheck to skip."))
        self.checkBox_AgentPaths.setText(_translate("DialogHydra", "Agent paths (agentPaths.duckdb, heavy)"))
        self.run_Hydra.setText(_translate("DialogHydra", "Run"))
