# -*- coding: utf-8 -*-
"""HyDRA (AgentFlow-DTA) dialog.

Layout: a common input strip (network, trip list, output directory, impedance)
above a two-tab stack.

  DTA tab - the dynamic loaders (point queue / node-conserving), with meso,
            micro, node refresh and the reroute/spillback controls.
  STA tab - static BPR assignment, solved in flow space (STA_METHOD).

The split is not cosmetic. Most DTA controls do nothing under STA_BPR -- route
chunks, node refresh, meso/micro, reroute fraction, LTM spillback, jam density
and the discharge factors are all ignored by a static assignment. Showing them
on the STA tab would imply they have an effect. Conversely the STA tab carries
the solver and VDF period, which mean nothing to a dynamic loading.

Widget names are unchanged from the single-page version so the dialog logic in
HydraAssignDialog_plugin.py keeps working; the DTA widgets simply moved parent.
"""

from qgis.PyQt import QtCore, QtWidgets


class Ui_DialogHydra(object):
    def setupUi(self, DialogHydra):
        DialogHydra.setObjectName("DialogHydra")
        DialogHydra.resize(980, 640)
        self.topLayout = QtWidgets.QHBoxLayout(DialogHydra)
        self.topLayout.setObjectName("topLayout")
        self.frame = QtWidgets.QFrame(DialogHydra)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setObjectName("frame")
        self.leftLayout = QtWidgets.QVBoxLayout(self.frame)
        self.leftLayout.setObjectName("leftLayout")

        # ---------------- common inputs (shared by both tabs) ----------------
        self.gridLayout_io = QtWidgets.QGridLayout()
        self.gridLayout_io.setObjectName("gridLayout_io")
        self.label_link = QtWidgets.QLabel(self.frame)
        self.label_link.setObjectName("label_link")
        self.gridLayout_io.addWidget(self.label_link, 0, 0, 1, 1)
        self.comboBox_LinkLayer = QtWidgets.QComboBox(self.frame)
        self.comboBox_LinkLayer.setObjectName("comboBox_LinkLayer")
        self.gridLayout_io.addWidget(self.comboBox_LinkLayer, 0, 1, 1, 2)
        self.label_node = QtWidgets.QLabel(self.frame)
        self.label_node.setObjectName("label_node")
        self.gridLayout_io.addWidget(self.label_node, 1, 0, 1, 1)
        self.comboBox_NodeLayer = QtWidgets.QComboBox(self.frame)
        self.comboBox_NodeLayer.setObjectName("comboBox_NodeLayer")
        self.gridLayout_io.addWidget(self.comboBox_NodeLayer, 1, 1, 1, 2)
        self.label_trip = QtWidgets.QLabel(self.frame)
        self.label_trip.setObjectName("label_trip")
        self.gridLayout_io.addWidget(self.label_trip, 2, 0, 1, 1)
        self.lineEdit_TripFile = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_TripFile.setObjectName("lineEdit_TripFile")
        self.gridLayout_io.addWidget(self.lineEdit_TripFile, 2, 1, 1, 1)
        self.browse_TripFile = QtWidgets.QPushButton(self.frame)
        self.browse_TripFile.setObjectName("browse_TripFile")
        self.gridLayout_io.addWidget(self.browse_TripFile, 2, 2, 1, 1)
        self.label_outdir = QtWidgets.QLabel(self.frame)
        self.label_outdir.setObjectName("label_outdir")
        self.gridLayout_io.addWidget(self.label_outdir, 3, 0, 1, 1)
        self.lineEdit_OutDir = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_OutDir.setObjectName("lineEdit_OutDir")
        self.gridLayout_io.addWidget(self.lineEdit_OutDir, 3, 1, 1, 1)
        self.browse_OutDir = QtWidgets.QPushButton(self.frame)
        self.browse_OutDir.setObjectName("browse_OutDir")
        self.gridLayout_io.addWidget(self.browse_OutDir, 3, 2, 1, 1)
        # Impedance is a scenario input like the trip list -- one copy, shared.
        # Duplicating it per tab would mean setting the toll policy on DTA and
        # finding it blank on STA.
        self.label_segparam = QtWidgets.QLabel(self.frame)
        self.label_segparam.setObjectName("label_segparam")
        self.gridLayout_io.addWidget(self.label_segparam, 4, 0, 1, 1)
        self.lineEdit_SegParams = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_SegParams.setObjectName("lineEdit_SegParams")
        self.gridLayout_io.addWidget(self.lineEdit_SegParams, 4, 1, 1, 1)
        self.browse_SegParams = QtWidgets.QPushButton(self.frame)
        self.browse_SegParams.setObjectName("browse_SegParams")
        self.gridLayout_io.addWidget(self.browse_SegParams, 4, 2, 1, 1)
        self.label_toll = QtWidgets.QLabel(self.frame)
        self.label_toll.setObjectName("label_toll")
        self.gridLayout_io.addWidget(self.label_toll, 5, 0, 1, 1)
        self.lineEdit_TollPolicy = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_TollPolicy.setObjectName("lineEdit_TollPolicy")
        self.gridLayout_io.addWidget(self.lineEdit_TollPolicy, 5, 1, 1, 1)
        self.browse_TollPolicy = QtWidgets.QPushButton(self.frame)
        self.browse_TollPolicy.setObjectName("browse_TollPolicy")
        self.gridLayout_io.addWidget(self.browse_TollPolicy, 5, 2, 1, 1)
        self.leftLayout.addLayout(self.gridLayout_io)

        # ---------------- the assignment-engine tabs ----------------
        self.tabWidget_Engine = QtWidgets.QTabWidget(self.frame)
        self.tabWidget_Engine.setObjectName("tabWidget_Engine")

        # ===================== DTA =====================
        self.page_DTA = QtWidgets.QWidget()
        self.page_DTA.setObjectName("page_DTA")
        self.dtaLayout = QtWidgets.QVBoxLayout(self.page_DTA)
        self.dtaLayout.setObjectName("dtaLayout")

        self.macroLayout = QtWidgets.QHBoxLayout()
        self.macroLayout.setObjectName("macroLayout")
        self.label_macro = QtWidgets.QLabel(self.page_DTA)
        self.label_macro.setObjectName("label_macro")
        self.macroLayout.addWidget(self.label_macro)
        self.comboBox_Macro = QtWidgets.QComboBox(self.page_DTA)
        self.comboBox_Macro.setObjectName("comboBox_Macro")
        for _ in range(3):
            self.comboBox_Macro.addItem("")
        self.macroLayout.addWidget(self.comboBox_Macro)
        self.dtaLayout.addLayout(self.macroLayout)

        self.groupBox_Equil = QtWidgets.QGroupBox(self.page_DTA)
        self.groupBox_Equil.setObjectName("groupBox_Equil")
        self.gridLayout_eq = QtWidgets.QGridLayout(self.groupBox_Equil)
        self.gridLayout_eq.setObjectName("gridLayout_eq")
        self.label_iters = QtWidgets.QLabel(self.groupBox_Equil)
        self.label_iters.setObjectName("label_iters")
        self.gridLayout_eq.addWidget(self.label_iters, 0, 0, 1, 1)
        self.lineEdit_Iters = QtWidgets.QLineEdit(self.groupBox_Equil)
        self.lineEdit_Iters.setObjectName("lineEdit_Iters")
        self.gridLayout_eq.addWidget(self.lineEdit_Iters, 0, 1, 1, 1)
        self.label_gap = QtWidgets.QLabel(self.groupBox_Equil)
        self.label_gap.setObjectName("label_gap")
        self.gridLayout_eq.addWidget(self.label_gap, 0, 2, 1, 1)
        self.lineEdit_Gap = QtWidgets.QLineEdit(self.groupBox_Equil)
        self.lineEdit_Gap.setObjectName("lineEdit_Gap")
        self.gridLayout_eq.addWidget(self.lineEdit_Gap, 0, 3, 1, 1)
        self.label_chunks = QtWidgets.QLabel(self.groupBox_Equil)
        self.label_chunks.setObjectName("label_chunks")
        self.gridLayout_eq.addWidget(self.label_chunks, 1, 0, 1, 1)
        self.lineEdit_Chunks = QtWidgets.QLineEdit(self.groupBox_Equil)
        self.lineEdit_Chunks.setObjectName("lineEdit_Chunks")
        self.gridLayout_eq.addWidget(self.lineEdit_Chunks, 1, 1, 1, 1)
        self.label_threads = QtWidgets.QLabel(self.groupBox_Equil)
        self.label_threads.setObjectName("label_threads")
        self.gridLayout_eq.addWidget(self.label_threads, 1, 2, 1, 1)
        self.lineEdit_Threads = QtWidgets.QLineEdit(self.groupBox_Equil)
        self.lineEdit_Threads.setObjectName("lineEdit_Threads")
        self.gridLayout_eq.addWidget(self.lineEdit_Threads, 1, 3, 1, 1)
        self.label_nodesched = QtWidgets.QLabel(self.groupBox_Equil)
        self.label_nodesched.setObjectName("label_nodesched")
        self.gridLayout_eq.addWidget(self.label_nodesched, 2, 0, 1, 1)
        self.comboBox_NodeSchedule = QtWidgets.QComboBox(self.groupBox_Equil)
        self.comboBox_NodeSchedule.setObjectName("comboBox_NodeSchedule")
        for _ in range(3):
            self.comboBox_NodeSchedule.addItem("")
        self.gridLayout_eq.addWidget(self.comboBox_NodeSchedule, 2, 1, 1, 3)
        self.dtaLayout.addWidget(self.groupBox_Equil)

        self.groupBox_MesoMicro = QtWidgets.QGroupBox(self.page_DTA)
        self.groupBox_MesoMicro.setObjectName("groupBox_MesoMicro")
        self.gridLayout_mm = QtWidgets.QGridLayout(self.groupBox_MesoMicro)
        self.gridLayout_mm.setObjectName("gridLayout_mm")
        self.label_meso = QtWidgets.QLabel(self.groupBox_MesoMicro)
        self.label_meso.setObjectName("label_meso")
        self.gridLayout_mm.addWidget(self.label_meso, 0, 0, 1, 1)
        self.lineEdit_MesoFtypes = QtWidgets.QLineEdit(self.groupBox_MesoMicro)
        self.lineEdit_MesoFtypes.setObjectName("lineEdit_MesoFtypes")
        self.gridLayout_mm.addWidget(self.lineEdit_MesoFtypes, 0, 1, 1, 3)
        self.checkBox_Micro = QtWidgets.QCheckBox(self.groupBox_MesoMicro)
        self.checkBox_Micro.setObjectName("checkBox_Micro")
        self.gridLayout_mm.addWidget(self.checkBox_Micro, 1, 0, 1, 1)
        self.lineEdit_MicroFtypes = QtWidgets.QLineEdit(self.groupBox_MesoMicro)
        self.lineEdit_MicroFtypes.setEnabled(False)
        self.lineEdit_MicroFtypes.setObjectName("lineEdit_MicroFtypes")
        self.gridLayout_mm.addWidget(self.lineEdit_MicroFtypes, 1, 1, 1, 1)
        self.label_coupling = QtWidgets.QLabel(self.groupBox_MesoMicro)
        self.label_coupling.setObjectName("label_coupling")
        self.gridLayout_mm.addWidget(self.label_coupling, 1, 2, 1, 1)
        self.comboBox_Coupling = QtWidgets.QComboBox(self.groupBox_MesoMicro)
        self.comboBox_Coupling.setEnabled(False)
        self.comboBox_Coupling.setObjectName("comboBox_Coupling")
        for _ in range(3):
            self.comboBox_Coupling.addItem("")
        self.gridLayout_mm.addWidget(self.comboBox_Coupling, 1, 3, 1, 1)
        self.label_microchoice = QtWidgets.QLabel(self.groupBox_MesoMicro)
        self.label_microchoice.setObjectName("label_microchoice")
        self.gridLayout_mm.addWidget(self.label_microchoice, 2, 0, 1, 1)
        self.comboBox_MicroChoice = QtWidgets.QComboBox(self.groupBox_MesoMicro)
        self.comboBox_MicroChoice.setEnabled(False)
        self.comboBox_MicroChoice.setObjectName("comboBox_MicroChoice")
        for _ in range(2):
            self.comboBox_MicroChoice.addItem("")
        self.gridLayout_mm.addWidget(self.comboBox_MicroChoice, 2, 1, 1, 3)
        self.dtaLayout.addWidget(self.groupBox_MesoMicro)

        self.groupBox_Advanced = QtWidgets.QGroupBox(self.page_DTA)
        self.groupBox_Advanced.setObjectName("groupBox_Advanced")
        self.gridLayout_adv = QtWidgets.QGridLayout(self.groupBox_Advanced)
        self.gridLayout_adv.setObjectName("gridLayout_adv")
        self.label_rerouteFrac = QtWidgets.QLabel(self.groupBox_Advanced)
        self.label_rerouteFrac.setObjectName("label_rerouteFrac")
        self.gridLayout_adv.addWidget(self.label_rerouteFrac, 0, 0, 1, 1)
        self.lineEdit_RerouteFraction = QtWidgets.QLineEdit(self.groupBox_Advanced)
        self.lineEdit_RerouteFraction.setObjectName("lineEdit_RerouteFraction")
        self.gridLayout_adv.addWidget(self.lineEdit_RerouteFraction, 0, 1, 1, 1)
        self.label_rerouteThr = QtWidgets.QLabel(self.groupBox_Advanced)
        self.label_rerouteThr.setObjectName("label_rerouteThr")
        self.gridLayout_adv.addWidget(self.label_rerouteThr, 0, 2, 1, 1)
        self.lineEdit_RerouteThreshold = QtWidgets.QLineEdit(self.groupBox_Advanced)
        self.lineEdit_RerouteThreshold.setObjectName("lineEdit_RerouteThreshold")
        self.gridLayout_adv.addWidget(self.lineEdit_RerouteThreshold, 0, 3, 1, 1)
        self.label_spillback = QtWidgets.QLabel(self.groupBox_Advanced)
        self.label_spillback.setObjectName("label_spillback")
        self.gridLayout_adv.addWidget(self.label_spillback, 1, 0, 1, 1)
        self.lineEdit_LtmSpillback = QtWidgets.QLineEdit(self.groupBox_Advanced)
        self.lineEdit_LtmSpillback.setObjectName("lineEdit_LtmSpillback")
        self.gridLayout_adv.addWidget(self.lineEdit_LtmSpillback, 1, 1, 1, 1)
        self.label_jam = QtWidgets.QLabel(self.groupBox_Advanced)
        self.label_jam.setObjectName("label_jam")
        self.gridLayout_adv.addWidget(self.label_jam, 1, 2, 1, 1)
        self.lineEdit_JamDensity = QtWidgets.QLineEdit(self.groupBox_Advanced)
        self.lineEdit_JamDensity.setObjectName("lineEdit_JamDensity")
        self.gridLayout_adv.addWidget(self.lineEdit_JamDensity, 1, 3, 1, 1)
        self.label_maxtrips = QtWidgets.QLabel(self.groupBox_Advanced)
        self.label_maxtrips.setObjectName("label_maxtrips")
        self.gridLayout_adv.addWidget(self.label_maxtrips, 2, 0, 1, 1)
        self.lineEdit_MaxTrips = QtWidgets.QLineEdit(self.groupBox_Advanced)
        self.lineEdit_MaxTrips.setObjectName("lineEdit_MaxTrips")
        self.gridLayout_adv.addWidget(self.lineEdit_MaxTrips, 2, 1, 1, 1)
        self.label_sample = QtWidgets.QLabel(self.groupBox_Advanced)
        self.label_sample.setObjectName("label_sample")
        self.gridLayout_adv.addWidget(self.label_sample, 2, 2, 1, 1)
        self.lineEdit_SampleEvery = QtWidgets.QLineEdit(self.groupBox_Advanced)
        self.lineEdit_SampleEvery.setObjectName("lineEdit_SampleEvery")
        self.gridLayout_adv.addWidget(self.lineEdit_SampleEvery, 2, 3, 1, 1)
        self.label_sampleSched = QtWidgets.QLabel(self.groupBox_Advanced)
        self.label_sampleSched.setObjectName("label_sampleSched")
        self.gridLayout_adv.addWidget(self.label_sampleSched, 3, 0, 1, 1)
        self.comboBox_SampleSchedule = QtWidgets.QComboBox(self.groupBox_Advanced)
        self.comboBox_SampleSchedule.setObjectName("comboBox_SampleSchedule")
        for _ in range(3):
            self.comboBox_SampleSchedule.addItem("")
        self.gridLayout_adv.addWidget(self.comboBox_SampleSchedule, 3, 1, 1, 1)
        self.label_sampleCustom = QtWidgets.QLabel(self.groupBox_Advanced)
        self.label_sampleCustom.setObjectName("label_sampleCustom")
        self.gridLayout_adv.addWidget(self.label_sampleCustom, 3, 2, 1, 1)
        self.lineEdit_SampleSchedule = QtWidgets.QLineEdit(self.groupBox_Advanced)
        self.lineEdit_SampleSchedule.setObjectName("lineEdit_SampleSchedule")
        self.gridLayout_adv.addWidget(self.lineEdit_SampleSchedule, 3, 3, 1, 1)
        self.checkBox_Checkpoint = QtWidgets.QCheckBox(self.groupBox_Advanced)
        self.checkBox_Checkpoint.setChecked(True)
        self.checkBox_Checkpoint.setObjectName("checkBox_Checkpoint")
        self.gridLayout_adv.addWidget(self.checkBox_Checkpoint, 4, 0, 1, 2)
        self.label_ckptEvery = QtWidgets.QLabel(self.groupBox_Advanced)
        self.label_ckptEvery.setObjectName("label_ckptEvery")
        self.gridLayout_adv.addWidget(self.label_ckptEvery, 4, 2, 1, 1)
        self.lineEdit_CheckpointEvery = QtWidgets.QLineEdit(self.groupBox_Advanced)
        self.lineEdit_CheckpointEvery.setObjectName("lineEdit_CheckpointEvery")
        self.gridLayout_adv.addWidget(self.lineEdit_CheckpointEvery, 4, 3, 1, 1)
        # Loading refresh: how often the per-link loader rebuilds arrivals within
        # a pass. Only meaningful for the Independent (point-queue/LTM) loader.
        self.label_loadRefresh = QtWidgets.QLabel(self.groupBox_Advanced)
        self.label_loadRefresh.setObjectName("label_loadRefresh")
        self.gridLayout_adv.addWidget(self.label_loadRefresh, 5, 0, 1, 1)
        self.comboBox_LoadRefresh = QtWidgets.QComboBox(self.groupBox_Advanced)
        self.comboBox_LoadRefresh.setObjectName("comboBox_LoadRefresh")
        for _ in range(2):
            self.comboBox_LoadRefresh.addItem("")
        self.gridLayout_adv.addWidget(self.comboBox_LoadRefresh, 5, 1, 1, 1)
        self.label_loadSchedule = QtWidgets.QLabel(self.groupBox_Advanced)
        self.label_loadSchedule.setObjectName("label_loadSchedule")
        self.gridLayout_adv.addWidget(self.label_loadSchedule, 5, 2, 1, 1)
        self.lineEdit_LoadSchedule = QtWidgets.QLineEdit(self.groupBox_Advanced)
        self.lineEdit_LoadSchedule.setObjectName("lineEdit_LoadSchedule")
        self.gridLayout_adv.addWidget(self.lineEdit_LoadSchedule, 5, 3, 1, 1)
        self.dtaLayout.addWidget(self.groupBox_Advanced)

        self.groupBox_Outputs = QtWidgets.QGroupBox(self.page_DTA)
        self.groupBox_Outputs.setObjectName("groupBox_Outputs")
        self.gridLayout_out = QtWidgets.QGridLayout(self.groupBox_Outputs)
        self.gridLayout_out.setObjectName("gridLayout_out")
        self.checkBox_AgentPlans = QtWidgets.QCheckBox(self.groupBox_Outputs)
        self.checkBox_AgentPlans.setChecked(True)
        self.checkBox_AgentPlans.setObjectName("checkBox_AgentPlans")
        self.gridLayout_out.addWidget(self.checkBox_AgentPlans, 0, 0, 1, 1)
        self.checkBox_AgentPaths = QtWidgets.QCheckBox(self.groupBox_Outputs)
        self.checkBox_AgentPaths.setChecked(True)
        self.checkBox_AgentPaths.setObjectName("checkBox_AgentPaths")
        self.gridLayout_out.addWidget(self.checkBox_AgentPaths, 0, 1, 1, 1)
        self.dtaLayout.addWidget(self.groupBox_Outputs)
        self.dtaLayout.addStretch(1)
        self.tabWidget_Engine.addTab(self.page_DTA, "")

        # ===================== STA =====================
        self.page_STA = QtWidgets.QWidget()
        self.page_STA.setObjectName("page_STA")
        self.staLayout = QtWidgets.QVBoxLayout(self.page_STA)
        self.staLayout.setObjectName("staLayout")

        self.groupBox_StaModel = QtWidgets.QGroupBox(self.page_STA)
        self.groupBox_StaModel.setObjectName("groupBox_StaModel")
        self.gridLayout_stamodel = QtWidgets.QGridLayout(self.groupBox_StaModel)
        self.gridLayout_stamodel.setObjectName("gridLayout_stamodel")
        self.label_staSolver = QtWidgets.QLabel(self.groupBox_StaModel)
        self.label_staSolver.setObjectName("label_staSolver")
        self.gridLayout_stamodel.addWidget(self.label_staSolver, 0, 0, 1, 1)
        self.comboBox_StaMethod = QtWidgets.QComboBox(self.groupBox_StaModel)
        self.comboBox_StaMethod.setObjectName("comboBox_StaMethod")
        for _ in range(5):
            self.comboBox_StaMethod.addItem("")
        self.gridLayout_stamodel.addWidget(self.comboBox_StaMethod, 0, 1, 1, 3)
        self.label_bprPeriod = QtWidgets.QLabel(self.groupBox_StaModel)
        self.label_bprPeriod.setObjectName("label_bprPeriod")
        self.gridLayout_stamodel.addWidget(self.label_bprPeriod, 1, 0, 1, 1)
        self.comboBox_BprPeriod = QtWidgets.QComboBox(self.groupBox_StaModel)
        self.comboBox_BprPeriod.setObjectName("comboBox_BprPeriod")
        for _ in range(3):
            self.comboBox_BprPeriod.addItem("")
        self.gridLayout_stamodel.addWidget(self.comboBox_BprPeriod, 1, 1, 1, 1)
        self.label_bprCoef = QtWidgets.QLabel(self.groupBox_StaModel)
        self.label_bprCoef.setObjectName("label_bprCoef")
        self.gridLayout_stamodel.addWidget(self.label_bprCoef, 1, 2, 1, 2)
        self.staLayout.addWidget(self.groupBox_StaModel)

        self.groupBox_StaEquil = QtWidgets.QGroupBox(self.page_STA)
        self.groupBox_StaEquil.setObjectName("groupBox_StaEquil")
        self.gridLayout_staeq = QtWidgets.QGridLayout(self.groupBox_StaEquil)
        self.gridLayout_staeq.setObjectName("gridLayout_staeq")
        self.label_staIters = QtWidgets.QLabel(self.groupBox_StaEquil)
        self.label_staIters.setObjectName("label_staIters")
        self.gridLayout_staeq.addWidget(self.label_staIters, 0, 0, 1, 1)
        self.lineEdit_StaIters = QtWidgets.QLineEdit(self.groupBox_StaEquil)
        self.lineEdit_StaIters.setObjectName("lineEdit_StaIters")
        self.gridLayout_staeq.addWidget(self.lineEdit_StaIters, 0, 1, 1, 1)
        self.label_staGap = QtWidgets.QLabel(self.groupBox_StaEquil)
        self.label_staGap.setObjectName("label_staGap")
        self.gridLayout_staeq.addWidget(self.label_staGap, 0, 2, 1, 1)
        self.lineEdit_StaGap = QtWidgets.QLineEdit(self.groupBox_StaEquil)
        self.lineEdit_StaGap.setObjectName("lineEdit_StaGap")
        self.gridLayout_staeq.addWidget(self.lineEdit_StaGap, 0, 3, 1, 1)
        self.label_staThreads = QtWidgets.QLabel(self.groupBox_StaEquil)
        self.label_staThreads.setObjectName("label_staThreads")
        self.gridLayout_staeq.addWidget(self.label_staThreads, 1, 0, 1, 1)
        self.lineEdit_StaThreads = QtWidgets.QLineEdit(self.groupBox_StaEquil)
        self.lineEdit_StaThreads.setObjectName("lineEdit_StaThreads")
        self.gridLayout_staeq.addWidget(self.lineEdit_StaThreads, 1, 1, 1, 1)
        self.staLayout.addWidget(self.groupBox_StaEquil)

        self.groupBox_StaDemand = QtWidgets.QGroupBox(self.page_STA)
        self.groupBox_StaDemand.setObjectName("groupBox_StaDemand")
        self.gridLayout_stadem = QtWidgets.QGridLayout(self.groupBox_StaDemand)
        self.gridLayout_stadem.setObjectName("gridLayout_stadem")
        self.label_staMaxTrips = QtWidgets.QLabel(self.groupBox_StaDemand)
        self.label_staMaxTrips.setObjectName("label_staMaxTrips")
        self.gridLayout_stadem.addWidget(self.label_staMaxTrips, 0, 0, 1, 1)
        self.lineEdit_StaMaxTrips = QtWidgets.QLineEdit(self.groupBox_StaDemand)
        self.lineEdit_StaMaxTrips.setObjectName("lineEdit_StaMaxTrips")
        self.gridLayout_stadem.addWidget(self.lineEdit_StaMaxTrips, 0, 1, 1, 1)
        self.label_staSample = QtWidgets.QLabel(self.groupBox_StaDemand)
        self.label_staSample.setObjectName("label_staSample")
        self.gridLayout_stadem.addWidget(self.label_staSample, 0, 2, 1, 1)
        self.lineEdit_StaSampleEvery = QtWidgets.QLineEdit(self.groupBox_StaDemand)
        self.lineEdit_StaSampleEvery.setObjectName("lineEdit_StaSampleEvery")
        self.gridLayout_stadem.addWidget(self.lineEdit_StaSampleEvery, 0, 3, 1, 1)
        self.label_staSampleSched = QtWidgets.QLabel(self.groupBox_StaDemand)
        self.label_staSampleSched.setObjectName("label_staSampleSched")
        self.gridLayout_stadem.addWidget(self.label_staSampleSched, 1, 0, 1, 1)
        self.comboBox_StaSampleSchedule = QtWidgets.QComboBox(self.groupBox_StaDemand)
        self.comboBox_StaSampleSchedule.setObjectName("comboBox_StaSampleSchedule")
        for _ in range(3):
            self.comboBox_StaSampleSchedule.addItem("")
        self.gridLayout_stadem.addWidget(self.comboBox_StaSampleSchedule, 1, 1, 1, 1)
        self.label_staSampleCustom = QtWidgets.QLabel(self.groupBox_StaDemand)
        self.label_staSampleCustom.setObjectName("label_staSampleCustom")
        self.gridLayout_stadem.addWidget(self.label_staSampleCustom, 1, 2, 1, 1)
        self.lineEdit_StaSampleSchedule = QtWidgets.QLineEdit(self.groupBox_StaDemand)
        self.lineEdit_StaSampleSchedule.setObjectName("lineEdit_StaSampleSchedule")
        self.gridLayout_stadem.addWidget(self.lineEdit_StaSampleSchedule, 1, 3, 1, 1)
        self.checkBox_StaCheckpoint = QtWidgets.QCheckBox(self.groupBox_StaDemand)
        self.checkBox_StaCheckpoint.setChecked(True)
        self.checkBox_StaCheckpoint.setObjectName("checkBox_StaCheckpoint")
        self.gridLayout_stadem.addWidget(self.checkBox_StaCheckpoint, 2, 0, 1, 2)
        self.label_staCkptEvery = QtWidgets.QLabel(self.groupBox_StaDemand)
        self.label_staCkptEvery.setObjectName("label_staCkptEvery")
        self.gridLayout_stadem.addWidget(self.label_staCkptEvery, 2, 2, 1, 1)
        self.lineEdit_StaCheckpointEvery = QtWidgets.QLineEdit(self.groupBox_StaDemand)
        self.lineEdit_StaCheckpointEvery.setObjectName("lineEdit_StaCheckpointEvery")
        self.gridLayout_stadem.addWidget(self.lineEdit_StaCheckpointEvery, 2, 3, 1, 1)
        self.staLayout.addWidget(self.groupBox_StaDemand)

        self.groupBox_StaOutputs = QtWidgets.QGroupBox(self.page_STA)
        self.groupBox_StaOutputs.setObjectName("groupBox_StaOutputs")
        self.gridLayout_staout = QtWidgets.QGridLayout(self.groupBox_StaOutputs)
        self.gridLayout_staout.setObjectName("gridLayout_staout")
        self.checkBox_StaAgentPlans = QtWidgets.QCheckBox(self.groupBox_StaOutputs)
        self.checkBox_StaAgentPlans.setChecked(True)
        self.checkBox_StaAgentPlans.setObjectName("checkBox_StaAgentPlans")
        self.gridLayout_staout.addWidget(self.checkBox_StaAgentPlans, 0, 0, 1, 1)
        self.checkBox_StaAgentPaths = QtWidgets.QCheckBox(self.groupBox_StaOutputs)
        self.checkBox_StaAgentPaths.setObjectName("checkBox_StaAgentPaths")
        self.gridLayout_staout.addWidget(self.checkBox_StaAgentPaths, 0, 1, 1, 1)
        self.checkBox_StaPathScale = QtWidgets.QCheckBox(self.groupBox_StaOutputs)
        self.checkBox_StaPathScale.setChecked(True)
        self.checkBox_StaPathScale.setObjectName("checkBox_StaPathScale")
        self.gridLayout_staout.addWidget(self.checkBox_StaPathScale, 1, 0, 1, 2)
        self.label_staPathWarn = QtWidgets.QLabel(self.groupBox_StaOutputs)
        self.label_staPathWarn.setWordWrap(True)
        self.label_staPathWarn.setObjectName("label_staPathWarn")
        self.gridLayout_staout.addWidget(self.label_staPathWarn, 2, 0, 1, 2)
        self.staLayout.addWidget(self.groupBox_StaOutputs)
        self.staLayout.addStretch(1)
        self.tabWidget_Engine.addTab(self.page_STA, "")

        self.leftLayout.addWidget(self.tabWidget_Engine)

        # ---------------- Run / Save / Cancel ----------------
        self.runLayout = QtWidgets.QHBoxLayout()
        self.runLayout.setObjectName("runLayout")
        self.run_Hydra = QtWidgets.QPushButton(self.frame)
        self.run_Hydra.setObjectName("run_Hydra")
        self.runLayout.addWidget(self.run_Hydra)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.frame)
        # Save persists and keeps the dialog open; Cancel is the only close.
        self.buttonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.StandardButton.Cancel
            | QtWidgets.QDialogButtonBox.StandardButton.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.runLayout.addWidget(self.buttonBox)
        self.leftLayout.addLayout(self.runLayout)
        self.topLayout.addWidget(self.frame)

        self.textBrowser = QtWidgets.QTextBrowser(DialogHydra)
        self.textBrowser.setMinimumSize(QtCore.QSize(320, 0))
        self.textBrowser.setOpenExternalLinks(True)
        self.textBrowser.setObjectName("textBrowser")
        self.topLayout.addWidget(self.textBrowser)

        self.retranslateUi(DialogHydra)
        # No preselected engine: the run mode is an explicit choice, so the DTA
        # flow-model combo and the STA solver both start unselected and Run
        # stays disabled until one is picked (see the dialog logic).
        self.comboBox_Macro.setCurrentIndex(-1)
        self.comboBox_StaMethod.setCurrentIndex(-1)
        self.comboBox_NodeSchedule.setCurrentIndex(2)
        self.comboBox_BprPeriod.setCurrentIndex(2)
        self.comboBox_LoadRefresh.setCurrentIndex(0)
        self.comboBox_StaSampleSchedule.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DialogHydra)

    def retranslateUi(self, DialogHydra):
        _translate = QtCore.QCoreApplication.translate
        DialogHydra.setWindowTitle(_translate("DialogHydra", "HyDRA (AgentFlow-DTA)"))

        # ---- common ----
        self.label_link.setText(_translate("DialogHydra", "Link layer (GeoPackage)"))
        self.label_node.setText(_translate("DialogHydra", "Node layer (GeoPackage)"))
        self.label_trip.setText(_translate("DialogHydra", "Trip list (.csv.gz)"))
        self.browse_TripFile.setText(_translate("DialogHydra", "..."))
        self.label_outdir.setText(_translate("DialogHydra", "Output directory"))
        self.lineEdit_OutDir.setPlaceholderText(_translate("DialogHydra", "(defaults to the scenario directory)"))
        self.lineEdit_OutDir.setToolTip(_translate("DialogHydra", "All HyDRA outputs (control file, log, link performance, agent plans/paths, checkpoint) are written here. Leave blank to use the scenario directory."))
        self.browse_OutDir.setText(_translate("DialogHydra", "..."))
        self.label_segparam.setText(_translate("DialogHydra", "Market Segments VOT (CSV)"))
        self.label_segparam.setToolTip(_translate("DialogHydra", "Per-marketVot generalized-cost coefficients. Shared by both engines; omit for travel-time-only routing."))
        self.browse_SegParams.setText(_translate("DialogHydra", "..."))
        self.label_toll.setText(_translate("DialogHydra", "Toll policy (CSV)"))
        self.browse_TollPolicy.setText(_translate("DialogHydra", "..."))

        self.tabWidget_Engine.setTabText(
            self.tabWidget_Engine.indexOf(self.page_DTA),
            _translate("DialogHydra", "DTA (dynamic)"))
        self.tabWidget_Engine.setTabText(
            self.tabWidget_Engine.indexOf(self.page_STA),
            _translate("DialogHydra", "STA (static)"))

        # ---- DTA ----
        self.label_macro.setText(_translate("DialogHydra", "Run Mode (flow model)"))
        self.comboBox_Macro.setToolTip(_translate("DialogHydra", "Preset configures the DNL flow model plus meso/micro defaults."))
        self.comboBox_Macro.setItemText(0, _translate("DialogHydra", "PointQueue (legacy per-link)"))
        self.comboBox_Macro.setItemText(1, _translate("DialogHydra", "Node + PointQueue (nodeDNL)"))
        self.comboBox_Macro.setItemText(2, _translate("DialogHydra", "Node + Spatial/LTM (nodeDNL)"))
        self.groupBox_Equil.setTitle(_translate("DialogHydra", "Equilibrium"))
        self.label_iters.setText(_translate("DialogHydra", "Max Iterations"))
        self.lineEdit_Iters.setText(_translate("DialogHydra", "10"))
        self.label_gap.setText(_translate("DialogHydra", "Relative Gap"))
        self.lineEdit_Gap.setText(_translate("DialogHydra", "0.01"))
        self.label_chunks.setText(_translate("DialogHydra", "Route Chunks"))
        self.lineEdit_Chunks.setText(_translate("DialogHydra", "10"))
        self.label_threads.setText(_translate("DialogHydra", "Threads (0=all)"))
        self.lineEdit_Threads.setText(_translate("DialogHydra", "0"))
        self.label_nodesched.setText(_translate("DialogHydra", "Node refresh"))
        self.comboBox_NodeSchedule.setToolTip(_translate("DialogHydra", "Node-DNL refresh stride for the DTA_Node* loaders: per_iter (fast, statewide), per_chunk (tight, county), or a hybrid ramp."))
        self.comboBox_NodeSchedule.setItemText(0, _translate("DialogHydra", "Per iteration (fast)"))
        self.comboBox_NodeSchedule.setItemText(1, _translate("DialogHydra", "Per chunk (tight)"))
        self.comboBox_NodeSchedule.setItemText(2, _translate("DialogHydra", "Hybrid (per-iter -> per-chunk)"))
        self.groupBox_MesoMicro.setTitle(_translate("DialogHydra", "Meso / Micro"))
        self.label_meso.setText(_translate("DialogHydra", "Meso FTYPEs"))
        self.checkBox_Micro.setText(_translate("DialogHydra", "Micro corridor"))
        self.label_coupling.setText(_translate("DialogHydra", "Coupling"))
        self.comboBox_Coupling.setItemText(0, _translate("DialogHydra", "oneway"))
        self.comboBox_Coupling.setItemText(1, _translate("DialogHydra", "twoway_frozen"))
        self.comboBox_Coupling.setItemText(2, _translate("DialogHydra", "twoway_full"))
        self.label_microchoice.setText(_translate("DialogHydra", "EL/GP choice"))
        self.comboBox_MicroChoice.setItemText(0, _translate("DialogHydra", "Meso logit"))
        self.comboBox_MicroChoice.setItemText(1, _translate("DialogHydra", "Endogenous (micro)"))
        self.groupBox_Advanced.setTitle(_translate("DialogHydra", "Advanced (afdta) -- rerouting, LTM, sampling"))
        self.label_rerouteFrac.setText(_translate("DialogHydra", "Reroute fraction (min)"))
        self.lineEdit_RerouteFraction.setText(_translate("DialogHydra", "0.05"))
        self.label_rerouteThr.setText(_translate("DialogHydra", "Reroute threshold (min)"))
        self.lineEdit_RerouteThreshold.setText(_translate("DialogHydra", "0.01"))
        self.label_spillback.setText(_translate("DialogHydra", "LTM max spillback (min)"))
        self.lineEdit_LtmSpillback.setText(_translate("DialogHydra", "20"))
        self.label_jam.setText(_translate("DialogHydra", "Jam density"))
        self.lineEdit_JamDensity.setText(_translate("DialogHydra", "240"))
        self.label_maxtrips.setText(_translate("DialogHydra", "Max trips (0=all)"))
        self.lineEdit_MaxTrips.setText(_translate("DialogHydra", "0"))
        self.label_sample.setText(_translate("DialogHydra", "Sample every"))
        self.lineEdit_SampleEvery.setText(_translate("DialogHydra", "1"))
        self.label_sampleSched.setText(_translate("DialogHydra", "Sampling schedule"))
        self.comboBox_SampleSchedule.setItemText(0, _translate("DialogHydra", "None (full demand)"))
        self.comboBox_SampleSchedule.setItemText(1, _translate("DialogHydra", "Progressive (25 -> 50 -> 100%)"))
        self.comboBox_SampleSchedule.setItemText(2, _translate("DialogHydra", "Custom"))
        self.label_sampleCustom.setText(_translate("DialogHydra", "Custom schedule"))
        self.lineEdit_SampleSchedule.setPlaceholderText(_translate("DialogHydra", "1-4:25, 5-8:50..."))
        self.checkBox_Checkpoint.setText(_translate("DialogHydra", "Write checkpoint (enables warm restart)"))
        self.label_ckptEvery.setText(_translate("DialogHydra", "Checkpoint every"))
        self.lineEdit_CheckpointEvery.setText(_translate("DialogHydra", "3"))
        self.label_loadRefresh.setText(_translate("DialogHydra", "Load refresh"))
        self.comboBox_LoadRefresh.setToolTip(_translate("DialogHydra", "How the per-link loader refreshes between chunks. Exact rebuilds every agent's arrivals; incremental updates only the keys that re-routed (faster, an approximation). Ignored by the node loaders."))
        self.comboBox_LoadRefresh.setItemText(0, _translate("DialogHydra", "Exact (rebuild all)"))
        self.comboBox_LoadRefresh.setItemText(1, _translate("DialogHydra", "Incremental (delta)"))
        self.label_loadSchedule.setText(_translate("DialogHydra", "Load schedule"))
        self.lineEdit_LoadSchedule.setPlaceholderText(_translate("DialogHydra", "(blank = every chunk)"))
        self.lineEdit_LoadSchedule.setToolTip(_translate("DialogHydra", "Per-link loader refresh stride, e.g. 1-9:iter, 10-15:chunk. Blank keeps the default (refresh after every chunk)."))
        self.groupBox_Outputs.setTitle(_translate("DialogHydra", "Outputs (link performance by macro/meso/micro is always written)"))
        self.checkBox_AgentPlans.setText(_translate("DialogHydra", "Agent plans (agentPlans_out.csv)"))
        self.checkBox_AgentPaths.setText(_translate("DialogHydra", "Agent paths (agentPaths.duckdb, heavy)"))

        # ---- STA ----
        self.groupBox_StaModel.setTitle(_translate("DialogHydra", "Static assignment (MACRO_MODEL = STA_BPR)"))
        self.label_staSolver.setText(_translate("DialogHydra", "Solver"))
        self.comboBox_StaMethod.setToolTip(_translate("DialogHydra", "All-or-nothing plus a step on the Beckmann objective. The conjugate variants remove Frank-Wolfe's zigzag near the optimum; legacy is the old DTA path-swap loop, which cannot converge a static assignment."))
        self.comboBox_StaMethod.setItemText(0, _translate("DialogHydra", "Bi-conjugate Frank-Wolfe (fastest)"))
        self.comboBox_StaMethod.setItemText(1, _translate("DialogHydra", "Conjugate Frank-Wolfe"))
        self.comboBox_StaMethod.setItemText(2, _translate("DialogHydra", "Frank-Wolfe"))
        self.comboBox_StaMethod.setItemText(3, _translate("DialogHydra", "MSA (step 1/k)"))
        self.comboBox_StaMethod.setItemText(4, _translate("DialogHydra", "Legacy path-swap (does not converge)"))
        self.label_bprPeriod.setText(_translate("DialogHydra", "VDF period"))
        self.comboBox_BprPeriod.setToolTip(_translate("DialogHydra", "Minutes the BPR curve aggregates over before pricing v/c. Volumes are still reported per 15 minutes; only travel time is held constant across the window."))
        self.comboBox_BprPeriod.setItemText(0, _translate("DialogHydra", "15 min"))
        self.comboBox_BprPeriod.setItemText(1, _translate("DialogHydra", "30 min"))
        self.comboBox_BprPeriod.setItemText(2, _translate("DialogHydra", "60 min (hourly)"))
        self.label_bprCoef.setText(_translate("DialogHydra", "alpha / beta come per-link from the ALPHA / BETA columns"))
        self.groupBox_StaEquil.setTitle(_translate("DialogHydra", "Equilibrium"))
        self.label_staIters.setText(_translate("DialogHydra", "Max Iterations"))
        self.lineEdit_StaIters.setText(_translate("DialogHydra", "15"))
        self.label_staGap.setText(_translate("DialogHydra", "Relative Gap"))
        self.lineEdit_StaGap.setText(_translate("DialogHydra", "0.01"))
        self.label_staThreads.setText(_translate("DialogHydra", "Threads (0=all)"))
        self.lineEdit_StaThreads.setText(_translate("DialogHydra", "0"))
        self.groupBox_StaDemand.setTitle(_translate("DialogHydra", "Demand and checkpoint"))
        self.label_staMaxTrips.setText(_translate("DialogHydra", "Max trips (0=all)"))
        self.lineEdit_StaMaxTrips.setText(_translate("DialogHydra", "0"))
        self.label_staSample.setText(_translate("DialogHydra", "Sample every"))
        self.lineEdit_StaSampleEvery.setText(_translate("DialogHydra", "1"))
        self.label_staSampleSched.setText(_translate("DialogHydra", "Sampling schedule"))
        self.comboBox_StaSampleSchedule.setItemText(0, _translate("DialogHydra", "None (full demand)"))
        self.comboBox_StaSampleSchedule.setItemText(1, _translate("DialogHydra", "Progressive (25 -> 50 -> 100%)"))
        self.comboBox_StaSampleSchedule.setItemText(2, _translate("DialogHydra", "Custom"))
        self.label_staSampleCustom.setText(_translate("DialogHydra", "Custom schedule"))
        self.lineEdit_StaSampleSchedule.setPlaceholderText(_translate("DialogHydra", "1-4:25, 5-8:50..."))
        self.checkBox_StaCheckpoint.setText(_translate("DialogHydra", "Write checkpoint (enables warm restart)"))
        self.label_staCkptEvery.setText(_translate("DialogHydra", "Checkpoint every"))
        self.lineEdit_StaCheckpointEvery.setText(_translate("DialogHydra", "3"))
        self.groupBox_StaOutputs.setTitle(_translate("DialogHydra", "Outputs (link performance is always written)"))
        self.checkBox_StaAgentPlans.setText(_translate("DialogHydra", "Agent plans (agentPlans_out.csv)"))
        self.checkBox_StaAgentPaths.setText(_translate("DialogHydra", "Agent paths (agentPaths.duckdb, heavy)"))
        self.checkBox_StaPathScale.setText(_translate("DialogHydra", "Path-flow reconciliation (sta_path_scale.csv)"))
        self.checkBox_StaPathScale.setToolTip(_translate("DialogHydra", "Per-link factor between the equilibrium volume and the volume implied by the written agent paths. Multiply a path-derived result (select-link, subarea, trace) by it to put it on the same footing as the reported volume."))
        self.label_staPathWarn.setText(_translate("DialogHydra", "Note: a Frank-Wolfe flow is an average of all-or-nothing solutions, so agent paths are the LAST all-or-nothing and do not re-sum to the link volumes. Link volumes are the equilibrium."))
