"""Shared MSR (Multi-Spatial Resolution) runner — single source of truth for
`msr.exe`. Used by both the standalone MSR editor (MSR_Dialog_plugin) and the
agentPlans (Trip List -> Table) step (trip_list2table_Dialog_Plugin).

MSR disaggregates a TSM-resolution trip list to the finer subarea subzones via
`msr disaggregate CONTROL.toml`, writing an MSR trip list (with O_MSR/D_MSR) and
the hourly MSR OD trip table. `msr sizeterms CONTROL.toml` (optional) recomputes
the destination size terms + within-parent probabilities first.

Inputs (all paths):
  - trip_list : TSM-resolution trip list (.csv.gz) -- the disaggregation source
  - subarea   : subarea parent-zone list (the TSM zones to split into subzones)
  - lookup    : 26k subzone land-use lookup (subzone -> parent TSM zone)
Size-term TOMLs default to the canonical model coefficients bundled in the
plugin config and are overridable via Config keys (no plugin edit needed).

The functions here are UI-agnostic: they validate, write the control, and run
the exe, returning (ok: bool, message: str) so any caller can surface it.
"""
import os
from .tsm_settings import Config


# Config key for each size-term TOML override (empty/unset -> bundled default).
SIZETERM_KEYS = {
    "sdt_resident": "sizeterm_sdt_res",
    "sdt_visitor":  "sizeterm_sdt_vis",
    "ldt":          "sizeterm_ldt",
    "truck":        "sizeterm_truck",
}


def bundled_sizeterm_tomls(settings=None):
    """The canonical SDT/LDT/truck size-term coefficient TOMLs bundled in the
    plugin config (the defaults, ignoring any Config override)."""
    settings = settings or Config()
    cfg = os.path.join(settings.get("plugin_dir"), "config").replace("\\", "/")
    return {
        "sdt_resident": f"{cfg}/sdt_resident_coefficients/size_terms.toml",
        "sdt_visitor":  f"{cfg}/sdt_visitor_coefficients/vis_tour_dest.toml",
        "ldt":          f"{cfg}/ldt_coefficients_toml/dest_choice.toml",
        "truck":        f"{cfg}/msr/truck_size_terms.toml",
    }


def sizeterm_tomls(settings=None):
    """The four size-term TOMLs msr reads: the bundled defaults, each overridable
    by a Config key (SIZETERM_KEYS) to point at a recalibrated TOML without
    editing the plugin. `msr disaggregate` recomputes the size terms from these
    on every run -- there is no cached size-term file to keep in sync."""
    settings = settings or Config()
    d = bundled_sizeterm_tomls(settings)
    return {k: (settings.get(SIZETERM_KEYS[k]) or d[k]) for k in d}


def default_outputs(scenario_dir):
    """The MSR trip list + hourly OD table paths (written into the scenario dir)."""
    scen = str(scenario_dir).replace("\\", "/")
    return f"{scen}/subarea_msr_triplist.csv.gz", f"{scen}/ELToD_MSR_Hourly_tt.csv"


def write_control(out_path, trip_list, subarea, lookup, msr_out, hourly_out,
                  settings=None, sizeterms_out=None):
    """Write the `msr disaggregate` control file (TOML): the size-term TOMLs,
    the 26k subzone land use (MSR lookup), the subarea parent-zone list, the
    TSM-resolution trip list, and the MSR outputs. `sizeterms_out` is the optional
    review CSV path used only by `msr sizeterms` (disaggregate ignores it)."""
    settings = settings or Config()
    tomls = sizeterm_tomls(settings)
    parent_col = settings.get("msr_parent_col") or "TSM_NG"
    index_col  = settings.get("msr_index_col") or "Index"
    od_res     = settings.get("msr_od_resolution") or "MSR"

    def fwd(p):
        return str(p).replace("\\", "/")

    lines = [
        "# MSR disaggregate control -- generated by the TSM panel.",
        "[size_terms]",
        f'sdt_resident = "{fwd(tomls["sdt_resident"])}"',
        f'sdt_visitor  = "{fwd(tomls["sdt_visitor"])}"',
        f'ldt          = "{fwd(tomls["ldt"])}"',
        f'truck        = "{fwd(tomls["truck"])}"',
        "",
        "[subzones]",
        f'path       = "{fwd(lookup)}"',
        f'parent_col = "{parent_col}"',
        f'index_col  = "{index_col}"',
        "",
        "[subarea]",
        f'path = "{fwd(subarea)}"',
        f'col  = "{parent_col}"',
        "",
        "[trips]",
        f'path = "{fwd(trip_list)}"',
        "",
        "[disaggregate]",
        f'od_resolution = "{od_res}"',
        'time_format   = "clock"',
        "",
        "[output]",
        f'sizeterms = "{fwd(sizeterms_out or (os.path.dirname(msr_out) + "/subarea_taz_sizeTerms.csv"))}"',
        f'msr_trips = "{fwd(msr_out)}"',
        f'hourly_od = "{fwd(hourly_out)}"',
        "",
    ]
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"Wrote MSR control: {out_path}")
    return out_path


def run(scenario_dir, trip_list, subarea, lookup, settings=None, export_sizeterms=False):
    """Validate inputs, write the control TOML, and run `msr disaggregate`.
    disaggregate always recomputes the size terms from the coefficient TOMLs, so
    no size-term file is cached. `export_sizeterms` additionally runs
    `msr sizeterms` to write the review CSV (subarea_taz_sizeTerms.csv) for QA.
    Returns (ok: bool, message: str)."""
    settings = settings or Config()
    if not scenario_dir:
        return False, "No scenario directory set (Output goes to the scenario directory)."

    msr_exe = settings.app_exe("utilities/msr.exe")
    if not os.path.exists(msr_exe):
        return False, f"msr.exe not found at: {msr_exe}"

    for label, p in (("trip list", trip_list),
                     ("subarea zone list", subarea),
                     ("subzone lookup (26k land use)", lookup)):
        if not (p and os.path.exists(p)):
            return False, f"MSR {label} is missing or not set:\n{p or '(empty)'}"

    scen = str(scenario_dir).replace("\\", "/")
    msr_out, hourly_out = default_outputs(scen)
    sizeterms_out = f"{scen}/subarea_taz_sizeTerms.csv"
    control = os.path.join(scenario_dir, "msr_control.toml")
    try:
        write_control(control, trip_list, subarea, lookup, msr_out, hourly_out,
                      settings, sizeterms_out=sizeterms_out)
    except Exception as e:
        return False, f"Error writing MSR control file: {e}"

    if export_sizeterms:
        try:
            r0 = settings.run_app([msr_exe, "sizeterms", control],
                                  log_path=f"{scen}/MSR_sizeterms.log", console=True)
        except Exception as e:
            return False, f"Error running `msr sizeterms`: {e}"
        if r0.returncode != 0:
            return False, "`msr sizeterms` failed. Check the console / MSR_sizeterms.log."

    try:
        r = settings.run_app([msr_exe, "disaggregate", control],
                             log_path=f"{scen}/MSR_disaggregate.log", console=True)
    except Exception as e:
        return False, f"Error running `msr disaggregate`: {e}"
    if r.returncode != 0:
        return False, "MSR disaggregation failed. Check the console / MSR_disaggregate.log."

    print(f"MSR disaggregation complete: {msr_out}")
    msg = ("MSR disaggregation complete.\n\n"
           f"MSR trip list:  {msr_out}\n"
           f"Hourly MSR OD:  {hourly_out}")
    if export_sizeterms:
        msg += f"\nSize-terms (QA): {sizeterms_out}"
    return True, msg
