# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/SDT_visitor.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_SDTVis(object):
    def setupUi(self, Dialog_SDTVis):
        Dialog_SDTVis.setObjectName("Dialog_SDTVis")
        Dialog_SDTVis.resize(628, 382)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(Dialog_SDTVis)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame = QtWidgets.QFrame(Dialog_SDTVis)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox_Landuse = QtWidgets.QComboBox(self.widget)
        self.comboBox_Landuse.setObjectName("comboBox_Landuse")
        self.horizontalLayout.addWidget(self.comboBox_Landuse)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.lineEdit_Skim = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_Skim.setObjectName("lineEdit_Skim")
        self.horizontalLayout_2.addWidget(self.lineEdit_Skim)
        self.browse_Skim = QtWidgets.QPushButton(self.widget)
        self.browse_Skim.setObjectName("browse_Skim")
        self.horizontalLayout_2.addWidget(self.browse_Skim)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.lineEdit_OutDir = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_OutDir.setObjectName("lineEdit_OutDir")
        self.horizontalLayout_3.addWidget(self.lineEdit_OutDir)
        self.browse_SDTVisOut = QtWidgets.QPushButton(self.widget)
        self.browse_SDTVisOut.setObjectName("browse_SDTVisOut")
        self.horizontalLayout_3.addWidget(self.browse_SDTVisOut)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_models = QtWidgets.QHBoxLayout()
        self.horizontalLayout_models.setObjectName("horizontalLayout_models")
        self.label_models = QtWidgets.QLabel(self.widget)
        self.label_models.setObjectName("label_models")
        self.horizontalLayout_models.addWidget(self.label_models)
        self.cb_runResident = QtWidgets.QCheckBox(self.widget)
        self.cb_runResident.setObjectName("cb_runResident")
        self.horizontalLayout_models.addWidget(self.cb_runResident)
        self.cb_runVisitor = QtWidgets.QCheckBox(self.widget)
        self.cb_runVisitor.setChecked(True)
        self.cb_runVisitor.setObjectName("cb_runVisitor")
        self.horizontalLayout_models.addWidget(self.cb_runVisitor)
        self.verticalLayout.addLayout(self.horizontalLayout_models)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Run_SDTVis = QtWidgets.QPushButton(self.widget)
        self.Run_SDTVis.setObjectName("Run_SDTVis")
        self.horizontalLayout_4.addWidget(self.Run_SDTVis)
        self.button_OkCancel = QtWidgets.QDialogButtonBox(self.widget)
        self.button_OkCancel.setOrientation(QtCore.Qt.Horizontal)
        self.button_OkCancel.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_OkCancel.setObjectName("button_OkCancel")
        self.horizontalLayout_4.addWidget(self.button_OkCancel)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6.addWidget(self.widget)
        self.textBrowser = QtWidgets.QTextBrowser(self.frame)
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout_6.addWidget(self.textBrowser)
        self.horizontalLayout_5.addWidget(self.frame)

        self.retranslateUi(Dialog_SDTVis)
        QtCore.QMetaObject.connectSlotsByName(Dialog_SDTVis)

    def retranslateUi(self, Dialog_SDTVis):
        _translate = QtCore.QCoreApplication.translate
        Dialog_SDTVis.setWindowTitle(_translate("Dialog_SDTVis", "Dialog"))
        self.label.setText(_translate("Dialog_SDTVis", "Land use layer"))
        self.label_4.setText(_translate("Dialog_SDTVis", "Skim File"))
        self.browse_Skim.setText(_translate("Dialog_SDTVis", "..."))
        self.label_6.setText(_translate("Dialog_SDTVis", "Output Directory"))
        self.browse_SDTVisOut.setText(_translate("Dialog_SDTVis", "..."))
        self.label_models.setText(_translate("Dialog_SDTVis", "Models to run:"))
        self.cb_runResident.setText(_translate("Dialog_SDTVis", "Resident"))
        self.cb_runVisitor.setText(_translate("Dialog_SDTVis", "Visitor"))
        self.Run_SDTVis.setText(_translate("Dialog_SDTVis", "Run SDT Vis"))
        self.textBrowser.setPlainText(_translate("Dialog_SDTVis", "Land-use layer:\n"
"SE data is maintained at the highest resolution (regional planning model level) with 25,000 zones to allow portablity between TSM and other egional models.  However the model is run at the TSM level with ~8700 zones for run timeand resource efficiency.  This layer is regional planning level and during the run, prepratory steps are run to aggregate the data to TSM level (Yes, TSM zonal strucute is desiged to nest quite well with regional model zone structure and is updated on annual basis).\n"
"\n"
"There might be instances where land-use data is updated for employment and other fields after running populationSIM and in all those instances, it\'s best to reproduce land-use files directly from this layer without needing to re-run POPSIM.\n"
"\n"
"\n"
"There are 8 DMA (designation market areas) per VisitFL.   Every year, VisitFL produces reports on tourisim in Florida and many of those details / distributions are directly used in TSM ranging from occupancy rates to travel party composition (size, age, income) length of the stay,  mode of travel (air,  auto), t op origin states as well as destinations by DMA. \n"
"\n"
"Occupancy Rates by Lodging Types: There are 3 types of lodging: Hote Room, staying with FL residents (resident Households) and Short-term rentals (AirB&B, Vibro). Most of this information is availble from DBPR and VistFL. \n"
"Households <DMA>\n"
"Hotels <DMA>\n"
"Short-tern Rentals <DMA>\n"
"\n"
"Skim File:\n"
"Produced from \"Skimmy\" Step.  DISTANCE table is required.  It is possible to expose the \"DISTANCE\" property where use many provide other vairables like  distance from congested skims or something of that nature,  however,  the user needs to edit UEC\'s (Excel spreadhseets > data tab) and thus it is decided to no expose \"DISTANCE\" table for user control.  See   model API for details on thsi control. \n"
"\n"
"Mode Share:\n"
"Rental Car share for OIA, MIA are collected by FDOT and are directly used as egress mode shares for AIR travelers from Airports to their hotel / household/ STR destination zones.  "))
