# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/summary_loadedNetwork.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.PyQt import QtCore, QtGui, QtWidgets


class Ui_QDailog_LoadedNetwork(object):
    def setupUi(self, QDailog_LoadedNetwork):
        QDailog_LoadedNetwork.setObjectName("QDailog_LoadedNetwork")
        QDailog_LoadedNetwork.resize(426, 190)
        self.gridLayout = QtWidgets.QGridLayout(QDailog_LoadedNetwork)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(QDailog_LoadedNetwork)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        self.label.setObjectName("label")
        self.comboBox_linkLayer = QtWidgets.QComboBox(self.splitter)
        self.comboBox_linkLayer.setObjectName("comboBox_linkLayer")
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(QDailog_LoadedNetwork)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.lineEdit_volume = QtWidgets.QLineEdit(QDailog_LoadedNetwork)
        self.lineEdit_volume.setObjectName("lineEdit_volume")
        self.horizontalLayout_4.addWidget(self.lineEdit_volume)
        self.browse_volume = QtWidgets.QPushButton(QDailog_LoadedNetwork)
        self.browse_volume.setObjectName("browse_volume")
        self.horizontalLayout_4.addWidget(self.browse_volume)
        self.gridLayout.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(QDailog_LoadedNetwork)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.lineEdit_loadedOut = QtWidgets.QLineEdit(QDailog_LoadedNetwork)
        self.lineEdit_loadedOut.setObjectName("lineEdit_loadedOut")
        self.horizontalLayout_3.addWidget(self.lineEdit_loadedOut)
        self.browse_loadedOut = QtWidgets.QPushButton(QDailog_LoadedNetwork)
        self.browse_loadedOut.setObjectName("browse_loadedOut")
        self.horizontalLayout_3.addWidget(self.browse_loadedOut)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.splitter_2 = QtWidgets.QSplitter(QDailog_LoadedNetwork)
        self.splitter_2.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.checkBox_isSubarea = QtWidgets.QCheckBox(self.splitter_2)
        self.checkBox_isSubarea.setObjectName("checkBox_isSubarea")
        self.checkBox_ValidationStats = QtWidgets.QCheckBox(self.splitter_2)
        self.checkBox_ValidationStats.setObjectName("checkBox_ValidationStats")
        self.gridLayout.addWidget(self.splitter_2, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(QDailog_LoadedNetwork)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.lineEdit_validationStats = QtWidgets.QLineEdit(QDailog_LoadedNetwork)
        self.lineEdit_validationStats.setEnabled(False)
        self.lineEdit_validationStats.setObjectName("lineEdit_validationStats")
        self.horizontalLayout_2.addWidget(self.lineEdit_validationStats)
        self.browse_ValidationStats = QtWidgets.QPushButton(QDailog_LoadedNetwork)
        self.browse_ValidationStats.setObjectName("browse_ValidationStats")
        self.horizontalLayout_2.addWidget(self.browse_ValidationStats)
        self.gridLayout.addLayout(self.horizontalLayout_2, 4, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_Run = QtWidgets.QPushButton(QDailog_LoadedNetwork)
        self.pushButton_Run.setObjectName("pushButton_Run")
        self.horizontalLayout.addWidget(self.pushButton_Run)
        # Settings export/import, same idea as the Configuration Table dialog.
        self.pushButton_Save = QtWidgets.QPushButton(QDailog_LoadedNetwork)
        self.pushButton_Save.setObjectName("pushButton_Save")
        self.horizontalLayout.addWidget(self.pushButton_Save)
        self.pushButton_Load = QtWidgets.QPushButton(QDailog_LoadedNetwork)
        self.pushButton_Load.setObjectName("pushButton_Load")
        self.horizontalLayout.addWidget(self.pushButton_Load)
        self.buttonBox_OkCancel = QtWidgets.QDialogButtonBox(QDailog_LoadedNetwork)
        self.buttonBox_OkCancel.setOrientation(QtCore.Qt.Orientation.Horizontal)
        # Save (not Ok): persists and leaves the dialog open. Cancel closes.
        self.buttonBox_OkCancel.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Save)
        self.buttonBox_OkCancel.setObjectName("buttonBox_OkCancel")
        self.horizontalLayout.addWidget(self.buttonBox_OkCancel)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 0, 1, 1)

        self.retranslateUi(QDailog_LoadedNetwork)
        # accepted is wired in the dialog logic (to update_settings, which keeps
        # the dialog open) -- deliberately NOT to accept() here.
        self.buttonBox_OkCancel.rejected.connect(QDailog_LoadedNetwork.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(QDailog_LoadedNetwork)

    def retranslateUi(self, QDailog_LoadedNetwork):
        _translate = QtCore.QCoreApplication.translate
        QDailog_LoadedNetwork.setWindowTitle(_translate("QDailog_LoadedNetwork", "LoadedNetwork"))
        self.label.setText(_translate("QDailog_LoadedNetwork", "Link layer "))
        self.comboBox_linkLayer.setToolTip(_translate("QDailog_LoadedNetwork", "choose link layer"))
        self.label_4.setText(_translate("QDailog_LoadedNetwork", "Volume File (csv)"))
        self.browse_volume.setToolTip(_translate("QDailog_LoadedNetwork", "save to csv file"))
        self.browse_volume.setText(_translate("QDailog_LoadedNetwork", "..."))
        self.label_5.setText(_translate("QDailog_LoadedNetwork", "Loaded File (gis)"))
        self.browse_loadedOut.setToolTip(_translate("QDailog_LoadedNetwork", "save to csv file"))
        self.browse_loadedOut.setText(_translate("QDailog_LoadedNetwork", "..."))
        self.checkBox_isSubarea.setText(_translate("QDailog_LoadedNetwork", "is a Subarea"))
        self.checkBox_ValidationStats.setText(_translate("QDailog_LoadedNetwork", "Run Validation Stats"))
        self.label_6.setText(_translate("QDailog_LoadedNetwork", "Validation Stats"))
        self.browse_ValidationStats.setToolTip(_translate("QDailog_LoadedNetwork", "save to csv file"))
        self.browse_ValidationStats.setText(_translate("QDailog_LoadedNetwork", "..."))
        self.pushButton_Run.setText(_translate("QDailog_LoadedNetwork", "Run"))
        self.pushButton_Save.setText(_translate("QDailog_LoadedNetwork", "Save settings..."))
        self.pushButton_Save.setToolTip(_translate("QDailog_LoadedNetwork", "Write the current settings to a JSON file."))
        self.pushButton_Load.setText(_translate("QDailog_LoadedNetwork", "Load settings..."))
        self.pushButton_Load.setToolTip(_translate("QDailog_LoadedNetwork", "Read settings from a JSON file and refresh this dialog."))
